name: Release Python Package

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]

    - name: Build the package
      run: python -m build

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        name: sargeom ${{ github.ref_name }}
        body: |
          `sargeom` is a Python package dedicated for Synthetic Aperture Radar (SAR) geometry calculations.
          This is a new release of the package. Please refer to the [CHANGELOG](./CHANGELOG.md) for more information.
        files: dist/*.whl
